name: Checks

on:
  push:
  pull_request:


jobs:
  build:
    name: Run checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]  # PYTHON VERSION
        os: [windows-latest]
    timeout-minutes: 60
    steps:
    - name: Set env
      shell: bash
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: actions/checkout@main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build windows executables
      shell: bash
      run: ./win_build.sh
    - name: Test windows executables
      shell: bash
      run: ./win_test.sh
