name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]  # PYTHON VERSION
        os: [windows-latest]
    timeout-minutes: 30
    steps:
    - name: Set env
      shell: bash
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - uses: actions/checkout@main
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build windows executables
      shell: bash
      run: ./win_build.sh
    - name: Release Assets
      uses: softprops/action-gh-release@v1
      with:
        name: DC tools for Windows ${{ env.RELEASE_VERSION }}
        draft: true
        prerelease: false
        body: |
            ![](https://img.shields.io/github/downloads/DC-Analysis/DC-tools-for-Windows/${{ env.RELEASE_VERSION }}/total.svg)
        files: |
          ./innosetup/Output/*.exe
